### PR TITLE
Support for debian buster

### PR DESCRIPTION
**Pull request by Jrmyy**
Small PR to fix Debian install and to add support for Debian Buster (issue with ansible)

### CODE REVIEW

**Comment by franklinkim** [comment]
Hi, is that just for buster or will it affect any future releases? if so we could do a strip suffix ...

**Comment by Jrmyy** [comment]
Hi,

In fact, the issue is between debian distributions (espacially sid debian distributions) and ansible, according to https://github.com/ansible/ansible/issues/19874.

I updated the PR accordingly.

**Comment by franklinkim** [comment]
thx

**Comment by pdesgarets** [comment]
Hi,
Thanks for the repo and @Jrmyy for the fix. @franklinkim do you know when it will be released on Ansible Galaxy ?
FYI there is something strange, the tag `1.9.1` links to https://github.com/weareinteractive/ansible-docker/commit/ba3e73c4528f0e0be1876f370350eccae2212a74 which updates the changelog with version `1.11.1` instead of `1.9.1`.

Best

**Comment by franklinkim** [comment]
@pdesgarets yeah, sorry, hit the wrong tag there. should be available any second

**Pull request merged**
