### PR TITLE
Configure DEB & RPM docker-ce repository urls as variables

### PR DESCRIPTION
**Pull request by matt6697**
- Configured DEB & RPM docker ce repository urls as variables to allow use of a local mirror of the official repository.
 - Updated readme with ànsible-role docgen` command.
 - Proposed changelog for v1.12.0
 - Updated travis-ci config with **--become parameter** as a replacement for deprecated **--sudo** parameter

### CODE REVIEW

**Comment by matt6697** [comment]
Hi @franklinkim, could you have a look at this PR and tell me if something has to be changed ?

**Comment by franklinkim** [comment]
THX

**Comment by matt6697** [comment]
Thanks for merging. Is v1.12 automatically pushed to ansible galaxy after some time or does it require manual action to make that new version available ?

**Comment by franklinkim** [comment]
Should have been automatically but I gave it a little push.

**Pull request merged**
